version: "3"

services:
  reverseProxy:
    image: nginx:1.23.1
    ports: 
      - 7777:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/www
    depends_on:
      - helloservice
      - goodbyeservice
    restart: unless-stopped
  
  helloservice:
    build:
      context: ../HelloService
  
  goodbyeservice:
    build:
      context: ../GoodbyeService
